# Generated by Django 3.0.6 on 2020-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_1', models.CharField(max_length=100)),
                ('choice_2', models.CharField(max_length=100)),
                ('choice_3', models.CharField(max_length=100)),
                ('choice_4', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=5)),
                ('correct_choice', models.CharField(choices=[('C1', 'Choice 1'), ('C2', 'Choice 2'), ('C3', 'Choice 3'), ('C4', 'Choice 4')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('questions', models.ManyToManyField(to='exam.Question')),
            ],
        ),
    ]
