# Generated by Django 3.0.6 on 2020-06-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(choices=[('CH1', 'Choice 1'), ('CH2', 'Choice 2'), ('CH3', 'Choice 3'), ('CH4', 'Choice 4')], max_length=3),
        ),
    ]
